### ISSUE TITLE
Знайти фото графічного редактора Paint в інтернеті

### ISSUE THREAD

**Issue by tetyana5678** [tetyana5678/praktuchna4#1]
Знайти найкраще фото в Інтернеті

**Comment by pppu8890-7** [comment]
Шукаю вже

**Comment by pppu8890-7** [comment]
![image](https://user-images.githubusercontent.com/74249207/98686281-0a899f00-2371-11eb-8e7c-c8696d826295.png)

**Comment by pppu8890-7** [comment]
Зображення знайдено

**Comment by tetyana5678** [comment]
Дякую
